version: '3.9'

services:
  app:
    image: 'node:14.5.0-alpine'
    working_dir: /home/node/app
    volumes:
      - ../:/home/node/app
    command: redis-commander --redis-host redis
    ports:
      - "8081:8081"
  redis:
    image: 'redis:7-alpine'
    ports:
      - '6379:6379'
